version: '3'

services:
  web:
    build:
      context: ./webserver
      dockerfile: .Dockerfile
    volumes:
      - ${APP_PATH}:/var/www/validator
    ports:
      - ${WEB_PORT}:80
    links:
      - app

  app:
    build:
      context: ./app
      dockerfile: .Dockerfile
    volumes:
      - ${APP_PATH}:/var/www/validator
    ports:
      - ${PHP_PORT}:9000
    environment:
      TZ: ${APP_TZ}
      PHP_XDEBUG_PORT: ${PHP_XDEBUG_PORT}

  redis:
    image: redis:5.0
    ports:
      - ${REDIS_PORT}:6379